[project]
name = "guitar-simulator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.1",
    "pyaudio>=0.2.14",
    "pydantic>=2.10.4",
]
